### ISSUE TITLE
I've got Unexpected non-whitespace character after JSON

### ISSUE THREAD

**Issue by jtuttas** [UnboundEducation/moodle-block_ube_ta#1]
Hello, just installed your Plugin on a Moodle 4.3 System and I think I've configured evertyhing correct (API Key, Endpoint etc). Wenn I try to place the Block in a Moodle Course an Press Save I've got the following error Message:

```
SyntaxError: Unexpected non-whitespace character after JSON at position 685 (line 1 column 686)
    at parse (<anonymous>)
    at https://service.joerg-tuttas.de/moodle/lib/javascript.php/1720079668/lib/jquery/jquery-3.7.1.min.js:2:77349
    at l (https://service.joerg-tuttas.de/moodle/lib/javascript.php/1720079668/lib/jquery/jquery-3.7.1.min.js:2:77466)
    at XMLHttpRequest.<anonymous> (https://service.joerg-tuttas.de/moodle/lib/javascript.php/1720079668/lib/jquery/jquery-3.7.1.min.js:2:80265)
```

Indeed the JSON that the Request returns looks malformed:

```json
{
    "blockid": 1038,
    "blockname": "ube_ta",
    "blockregion": "",
    "pagehash": "7ba598c249237a9ae9a2120da6b6269d",
    "config_opener": "Hallo, wie kann ich Dir helfen?",
    "config_showsource": 1,
    "config_startopen": 1,
    "config_temperature": "0.6",
    "config_sourcecount": "5",
    "config_questionprompt": "",
    "config_condenseprompt": "",
    "config_customcss": "",
    "mform_isexpanded_id_filter_header_ztJlyF4u9B7LaCd": 1,
    "config_quick_filters": 0,
    "config_filters": "",
    "bui_pagetypepattern": "course-view-*",
    "bui_defaultregion": "side-pre",
    "bui_defaultweight": "2",
    "bui_visible": "1",
    "bui_region": "side-pre",
    "bui_weight": "-5",
    "bui_editingatfrontpage": false,
    "bui_parentcontextid": "11006",
    "bui_contexts": "0",
    "bui_subpagepattern": "%@NULL@%"
}[
    {
        "error": false,
        "data": {
            "submitted": true,
            "data": "null"
        }
    }
]
```

**Comment by jtuttas** [comment]
Seemed to be a server side problem !
